baseURL = "https://laurakalbag.com"
languageCode = "en-GB"
title = "Laura Kalbag"
theme = "static-kalbag"
[author]
	name = "Laura Kalbag"
	email = "hi@laurakalbag.com"
[permalinks]
	pages = "/:slug/"
	posts = "/:filename/"
[params]
	image = "/site-feature.png" # Default other stuff image for site
	publisherLogo = "/site-feature.png" # Default other stuff image for site
	publisher = "Laura Kalbag"
	twitter = "laurakalbag"
	facebook = "laurakalbag"
[imaging]
# Default resample filter used for resizing. Default is Box,
# a simple and fast averaging filter appropriate for downscaling.
# See https://github.com/disintegration/imaging
resampleFilter = "Gaussian"
# Default JPEG quality setting. Default is 75.
quality = 100
# Anchor used when cropping pictures.
# Default is "smart" which does Smart Cropping, using https://github.com/muesli/smartcrop
# Smart Cropping is content aware and tries to find the best crop for each image.
# Valid values are Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight
anchor = "smart"