baseURL = "https://laurakalbag.com"
languageCode = "en-GB"
title = "Laura Kalbag"
theme = "static-kalbag"
[permalinks]
	pages = "/:filename/"
	posts = "/:filename/"
	projects = "/project/:filename/"
[params]
	feature_image = "https://laurakalbag.com/android-chrome-512x512.png" # Default Open Graph image for site