baseURL = "https://laurakalbag.com"
languageCode = "en-GB"
title = "Laura Kalbag"
theme = "static-kalbag"
[permalinks]
	pages = "/:slug/"
	posts = "/:filename/"
	projects = "/project/:filename/"
[params]
	feature_image = "/site-feature.png" # Default Open Graph image for site
	image = "/site-feature.png" # Default other stuff image for site