#!/bin/bash

# Uses Hugo to create a new photo post based on the current date
# e.g., new my-awesome-blog-post will create content/YYYY/MM/DD/HH/MM/_index.md

pathPrefix="photos/"
postPath=$(date +'%Y/%m/%d/%H/%M')
pathSuffix="/index.md"

postPath="$pathPrefix$postPath$pathSuffix"

hugo new $postPath
