baseURL = "https://laurakalbag.com"
languageCode = "en-GB"
title = "Laura Kalbag"
theme = "static-kalbag"
[permalinks]
	pages = "/:filename/"
	posts = "/:filename/"
	projects = "/project/:filename/"
# images = [
#  "https://laurakalbag.com/images/" # Default Open Graph image for site
#]